####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-polymer
Description: OPM module for polymer simulations
Version: 2015.10
Label: 2015.10
Maintainer: atgeirr@sintef.no
MaintainerName: Atgeirr F. Rasmussen
Url: http://opm-project.org
Depends: opm-common opm-autodiff
